### ISSUE TITLE
Formatting/encoding

### ISSUE THREAD

**Issue by volodymyr-kushnir** [mr-sychevskyi/BSA-17-JS-Hometask1#7]
Hola. So it looks good so far, but it's kind of hard to actually read the article here on GitHub.
I would suggest switching to **.md instead of .txt** and **adding some Markdown formatting**, at least making headers stand-out a bit more. Also there's something wrong with encoding probably, because raw mode gives me [**unreadable text**](https://raw.githubusercontent.com/mr-sychevskyi/BSA-17-JS-Hometask1/master/article.txt). Could you please check whether your files are in **UTF-8 encoding**? Thanks.

Also, you can close this issue automatically if you use "Fixes #7" as your commit message.

**Comment by volodymyr-kushnir** [comment]
The article is good though. IMO it's very interesting how education will change over the course of the next decade. I think that self-education will come forward and traditional universities will slowly fade unless they change their system (bet on the environment and collaboration, for example, because self-education clearly lacks those). At least I don't see my kids going to Ukrainian universities 17-18 years from now — that would be a waste of time and money I guess.

**Comment by mr-sychevskyi** [comment]
Fix #3

**Comment by volodymyr-kushnir** [comment]
@mr-sychevskyi, nope, commit message. Коли коммітиш, то дописуй "fixes #3" до повідомлення комміту, типу `git commit -m "I did all the work (I fixed #3, and this closes #7)"`. GitHub парсить fixed/fixes, closed/closes, resolved/resolves.

**Comment by volodymyr-kushnir** [comment]
@mr-sychevskyi ой, також [**ще більше підказок тут**](https://github.com/volodymyr-kushnir/agenda).
